###

@baseUrl = http://{{KULALA_HOST}}:{{KULALA_PORT}}


### Get all accounts

GET {{baseUrl}}/api/git/accounts HTTP/1.1
Accept: application/json


### 

@platformId = "9c58c2f3-cdf2-4e30-b02a-9843f874c825"


### Create a account

POST {{baseUrl}}/api/git/accounts HTTP/1.1
Content-Type: application/json

{
  "Name": "icicle",
  "PlatformId": {{platformId}},
  "KEY": "LSKJFLSD"
}


### 

@accountId = e687b754-8eef-4bee-844c-fb0b15c37672
### Get an account
GET {{baseUrl}}/api/git/accounts/{{accountId}} HTTP/1.1
Content-Type: application/json

### Update an account
# PATCH {{baseUrl}}/api/git/accounts/{{accountId}} HTTP/1.1
# Content-Type: application/json
#
### Delete an account
# DELETE {{baseUrl}}/api/git/accounts/{{accountId}} HTTP/1.1

###

