###

@baseUrl = http://{{KULALA_HOST}}:{{KULALA_PORT}}


### Get all accounts

GET {{baseUrl}}/api/git/accounts HTTP/1.1
Accept: application/json


### 

@platformId = "24ad2af2-2ff9-48f7-a50a-22aba433649a"


### Create a account

POST {{baseUrl}}/api/git/accounts HTTP/1.1
Content-Type: application/json

{
  "Name": "icicle",
  "PlatformId": {{platformId}}
}


### 

@accountId = da1c8995-cf55-4fc9-80c4-8525cbbf1a18
### Get an account
GET {{baseUrl}}/api/git/accounts/{{accountId}} HTTP/1.1
Content-Type: application/json

### Update an account
PATCH {{baseUrl}}/api/git/accounts/{{accountId}} HTTP/1.1
Content-Type: application/json

{
  "Clones": 100,
  "Followers": 50,
  "Forks": 25,
  "Stars": 200,
  "Views": 500,
  "Watchers": 75
}

### Delete an account
DELETE {{baseUrl}}/api/git/accounts/{{accountId}} HTTP/1.1

###

