@githubUrl = https://api.github.com
@repo = harvest
@owner = icicle-ai

# Metrics: Stars (stargazers_count), Forks (forks_count), Watchers (watchers_count)

GET {{githubUrl}}/repos/{{owner}}/{{repo}}
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

### 
GET {{githubUrl}}/orgs/{{owner}}
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

###
GET {{githubUrl}}/repos/{{owner}}/{{repo}}/traffic/views
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

###
GET {{githubUrl}}/repos/{{owner}}/{{repo}}/traffic/clones
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

###
GET {{githubUrl}}/repos/{{owner}}/{{repo}}/traffic/popular/paths
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

###
GET {{githubUrl}}/repos/{{owner}}/{{repo}}/traffic/popular/referrers
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

