###

@baseUrl = {{BASE_URL}}
### Health Check - Verify database connectivity

GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
X-Tapis-Token: {{Tapis_Token}}


###


### List all available routes

GET {{baseUrl}}/routes HTTP/1.1
Accept: application/json
X-Tapis-Token: {{Tapis_Token}}

###

