###

@baseUrl = {{BASE_URL}}


### Get all accounts

GET {{baseUrl}}/api/github/accounts HTTP/1.1
Accept: application/json
X-Tapis-Token: {{Tapis_Token}}

### 



### Create a account

POST {{baseUrl}}/api/github/accounts HTTP/1.1
Content-Type: application/json

{
  "Name": "icicle",
  "KEY": "LSKJFLSD"
}


### 

@accountId = 1
### Get an account
GET {{baseUrl}}/api/github/accounts/{{accountId}} HTTP/1.1
Content-Type: application/json

### Update an account
# PATCH {{baseUrl}}/api/github/accounts/{{accountId}} HTTP/1.1
# Content-Type: application/json
#
### Delete an account
# DELETE {{baseUrl}}/api/github/accounts/{{accountId}} HTTP/1.1

###

