###

@baseUrl = {{BASE_URL}}


### Get all repos

GET {{baseUrl}}/api/github/repos HTTP/1.1
Accept: application/json
X-Tapis-Token: {{Tapis_Token}}


### 


### Create a repo

POST {{baseUrl}}/api/github/repos HTTP/1.1
Content-Type: application/json

{
  "Name": "kitty",
  "Clones": 0,
  "Followers": 0,
  "Forks": 0,
  "Stars": 0,
  "Views": 0,
  "Watchers": 0
}


### 

@repoId = 1
### Get a repo
GET {{baseUrl}}/api/github/repos/{{repoId}} HTTP/1.1
Content-Type: application/json
X-Tapis-Token: {{Tapis_Token}}


### Delete a repo
DELETE {{baseUrl}}/api/github/repos/{{repoId}} HTTP/1.1

###

